version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - docker run --rm -v $PWD:/my-app denvazh/gatling -sf /my-app/src/main/test -s ok.SampleAppSpringBootTest
